// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFZIG-xeFvzJMFgkxk1MyM3AFJrPZ89Eg',
    appId: '1:892285200568:web:33d0e2b04e9483df122c4d',
    messagingSenderId: '892285200568',
    projectId: 'authmajorproject',
    authDomain: 'authmajorproject.firebaseapp.com',
    storageBucket: 'authmajorproject.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7IxpYNLx38Y9I0oSIeKY9bmpvZ1JVK_w',
    appId: '1:892285200568:android:10bab53fc4a5b7b4122c4d',
    messagingSenderId: '892285200568',
    projectId: 'authmajorproject',
    storageBucket: 'authmajorproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzvy5YGGPeqs_M0MQZeWvDl4fAoBySXek',
    appId: '1:892285200568:ios:b6acf5c83576d541122c4d',
    messagingSenderId: '892285200568',
    projectId: 'authmajorproject',
    storageBucket: 'authmajorproject.firebasestorage.app',
    iosBundleId: 'com.example.majorUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzvy5YGGPeqs_M0MQZeWvDl4fAoBySXek',
    appId: '1:892285200568:ios:b6acf5c83576d541122c4d',
    messagingSenderId: '892285200568',
    projectId: 'authmajorproject',
    storageBucket: 'authmajorproject.firebasestorage.app',
    iosBundleId: 'com.example.majorUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFZIG-xeFvzJMFgkxk1MyM3AFJrPZ89Eg',
    appId: '1:892285200568:web:f9320499acd1c455122c4d',
    messagingSenderId: '892285200568',
    projectId: 'authmajorproject',
    authDomain: 'authmajorproject.firebaseapp.com',
    storageBucket: 'authmajorproject.firebasestorage.app',
  );
}
